Makefile.am: use BUILT_SOURCES instead of BUILD_SOURCES
Since commit f7a354dd7991bda57ab8b26d6491687d777f88da ("Generate image headers from their PNG source, while still including them in dist tarball")
headers files are generated from autotools by using BUILD_SOURCES variable.

But when generating header files, it is important to generate the files before the
rest of the sources are compiled. So, the BUILT_SOURCES variable must be used in
this case.

Fixes:

psplash.c:17:10: fatal error: psplash-bar-img.h: No such file or directory
 #include "psplash-bar-img.h"

Signed-off-by: Pierre-Jean Texier <pjtexier@koncepto.io>